// Turns skills/<name>/SKILL.md into mcp/skills.generated.ts, so the MCP server can offer the same instructions as prompts
// (for GPT and any client without skills support). The SKILL.md files stay the single source of truth.
// Run `npm run build:skills` after editing one; a test fails if the generated file is out of date.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export function skillsSource(dir = path.join(root, 'skills')) {
  const skills = readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()
    .map((folder) => {
      const text = readFileSync(path.join(dir, folder, 'SKILL.md'), 'utf8').replace(/\r\n/g, '\n');
      const m = /^---\n([\s\S]*?)\n---\n+([\s\S]*)$/.exec(text);
      if (!m) throw new Error(`${folder}/SKILL.md has no front matter`);
      const field = (key) => {
        const v = new RegExp(`^${key}:\\s*(.+)$`, 'm').exec(m[1])?.[1].trim();
        if (!v) throw new Error(`${folder}/SKILL.md has no ${key}`);
        return v.startsWith('"') ? JSON.parse(v) : v;
      };
      const body = m[2].trim();
      const tag = /Use `skill: "([^"]+)"`/.exec(body)?.[1];
      if (!tag) throw new Error(`${folder}/SKILL.md must say which skill tag to use: Use \`skill: "…"\`.`);
      return { id: field('name').replace(/^mdedit-/, '').replace(/-/g, '_'), name: field('name'), description: field('description'), tag, body };
    });
  return `// Generated by scripts/skills.mjs from skills/*/SKILL.md. Do not edit; run \`npm run build:skills\`.\nexport const SKILLS: { id: string; name: string; description: string; tag: string; body: string }[] = ${JSON.stringify(skills, null, 2)};\n`;
}

export function writeSkills() {
  writeFileSync(path.join(root, 'mcp', 'skills.generated.ts'), skillsSource());
}

if (process.argv[1] === fileURLToPath(import.meta.url)) writeSkills();
